### ISSUE TITLE
SilkTouch/Spawners Endless Exp Glitch

### ISSUE THREAD

**Issue by MCTyler** [MnMaxon/AutoPickup#5]
I need to be disable Auto Exp just for Spawners. I use [CMI](https://www.spigotmc.org/resources/cmi-ranks-kits-portals-essentials-mysql-sqlite-bungeecord.3742/) that allows SilkTouch Mining of Spawners and Players can get Endless Exp by "Harvesting" Spawners over and over again. CMI has a setting to Disable Exp Drops if using SilkTouch to Harvest Spawners but this Plugin over rides it and allows continuous Exp gain from Spawners. Thats the only block I need to be able to turn off.

Turning Block Exp off Works (for all Blocks) but in a Prison Mine, Players can steal other Players Exp if this toggled off.

**Comment by ThePhilderbeast** [comment]
this repo isnt maintained, take a look at my fork for the current source and log the issues there if it persists.
