### ISSUE TITLE
Interferes with McMMO fishing

### ISSUE THREAD

**Issue by Iiridayn** [MnMaxon/AutoPickup#6]
When installed it changes the fishing results from McMMO; traps (TNT, poison) still activate, but stay in place, and all other drops are as vanilla (once `Override_Vanilla_Treasures` is turned off). It's a bit sad to miss the "touch of magic" catches, and the fishing experience becomes a bit bland overall.

**Comment by Iiridayn** [comment]
Installed - can't disable mob pickups from the UI - also quite like them generally.

Relevant locations:
- https://github.com/MnMaxon/AutoPickup/blob/master/src/main/java/me/MnMaxon/AutoPickup/MainListener.java#L198
- https://github.com/mcMMO-Dev/mcMMO/blob/aee60f2c098238858b0f40b6d06bc4219a6b42d4/src/main/java/com/gmail/nossr50/listeners/PlayerListener.java#L206

Are both high priority, and both fire (which was removing vanilla loot, removed config option `Override_Vanilla_Treasures` and they returned)

Normal priority handler:
- https://github.com/mcMMO-Dev/mcMMO/blob/aee60f2c098238858b0f40b6d06bc4219a6b42d4/src/main/java/com/gmail/nossr50/listeners/PlayerListener.java#L258
- goes to https://github.com/mcMMO-Dev/mcMMO/blob/aee60f2c098238858b0f40b6d06bc4219a6b42d4/src/main/java/com/gmail/nossr50/skills/fishing/FishingManager.java#L299
- which calls https://github.com/mcMMO-Dev/mcMMO/blob/aee60f2c098238858b0f40b6d06bc4219a6b42d4/src/main/java/com/gmail/nossr50/skills/fishing/FishingManager.java#L474

I know mcMMO's `getFishingTreasure` is getting called, since the "touch of magic" message fires occasionally, which is gated in `handleFishing` behind the result. Similarly, the event must not be canceled yet, for the same reason. On line 328 it sets the ItemStack to the treasure and... ? I get a `minecraft:fish` only. Why? Can we fix it?

**Comment by Iiridayn** [comment]
Versions: mcMMO as linked (Jenkins download, final commit pre-1.13 work), Spigot git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT), Auto Pickup 5.0.3.

**Comment by ThePhilderbeast** [comment]
this repo isn't maintained, please check this against my fork
